### ISSUE TITLE
bug: filtering with max/min monthly rent returns a 500

### ISSUE THREAD

**Issue by ludtkemorgan** [metrotranscom/doorway#696]
**Describe the bug**
On the homepage enter a number into the max rent field (e.g "1887") and nothing is returned. If you inspect the call a 500 response is returned.

This happens when doing the filter from either the home page or the filter drawer on the listings page.

The backend error:
```
{
    "context": "ExceptionsHandler",
    "level": "error",
    "message": "\nInvalid `prisma.$queryRawUnsafe()` invocation:\n\n\nRaw query failed. Code: `22P02`. Message: `ERROR: invalid input syntax for type integer: \"1979.00\"`",
    "stack": [
        "PrismaClientKnownRequestError: \nInvalid `prisma.$queryRawUnsafe()` invocation:\n\n\nRaw query failed. Code: `22P02`. Message: `ERROR: invalid input syntax for type integer: \"1979.00\"`\n    at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6877)\n    at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6211)\n    at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5919)\n    at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)\n    at async ListingService.listCombined (/app/dist/src/services/listing.service.js:208:28)\n    at async ListingController.getCombined (/app/dist/src/controllers/listing.controller.js:61:22)"
    ],
    "timestamp": "2024-06-20T17:59:35.905Z"
}
```

*side bug: the clearing of the filter also does not work*

**Comment by sarahlazarich** [comment]
fixed!!!!!!
